version: "3.9"
services:
  nginx:
    image: ghcr.io/blixthalka/swedish_retail_index_web:master
    ports:
      - 80:80
      - 443:443
    depends_on:
      - core
    volumes:
      - /srindex/certbot/www:/var/www/certbot/:ro
      - /srindex/certbot/conf/:/etc/letsencrypt/:ro
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  core:
    image: ghcr.io/blixthalka/swedish_retail_index_core:master
    expose:
      - "8082"
      - "7082"
    ports:
      - 7082:7082
    volumes:
     - "/swedish_retail_index/mnesia/:/swedish_retail_index/mnesia/:rw"
  certbot:
    image: certbot/certbot:latest
    volumes:
      - /srindex/certbot/www/:/var/www/certbot/:rw
      - /srindex/certbot/conf/:/etc/letsencrypt/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"